spring:
  application:
    name: oauth2-security-server
  datasource:
    url: jdbc:mariadb://localhost:3317/test
    username: root
    password: 654321
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
#  sql:
#    init:
#      schema-locations:
#        - classpath:sql/oauth2-authorization-consent-schema.sql
#        - classpath:sql/oauth2-authorization-schema.sql
#        - classpath:sql/oauth2-registered-client-schema.sql
#      mode: always
#      platform: mariadb

server:
  port: 9000
  error:
    include-message: always
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"