server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mariadb://localhost:3317/customer
    username: root
    password: 654321
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
