spring:
  application:
    name: oauth2-security-server
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/authorized"
            scope: message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000

server:
  port: 8086
  error:
    include-message: always
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"