spring:
  application:
    name: fraud
  datasource:
    url: jdbc:mariadb://localhost:3317/fraud
    username: root
    password: 654321
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
