spring:
  application:
    name: producer

server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"